In [46]:
# 넘파이를 자유자재로 써서 행렬 계산을 해야하니까.
import numpy as np
from numpy.lib import stride_tricks as st

In [47]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
# a.bytes()
# a.butes()[]
# a.data

In [53]:
print(a)
print("a.shape:", a.shape)
print("a.srides:", a.strides)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
a.shape: (4, 4)
a.srides: (16, 4)


In [136]:
window = 2
shape = a.shape[:-1] + (a.shape[-1] - window + 1, window)
print(shape, "횟수, 윈도우높이, 윈도우폭")
strides = a.strides + (a.strides[-1],)
print(strides, "다음열바이트, 1개크기, 건너뛸단위") 
print(a.itemsize,"itemsize")

(9, 2) 횟수, 윈도우높이, 윈도우폭
(4, 4) 다음열바이트, 1개크기, 건너뛸단위
4 itemsize


In [138]:
shape = (12,2,2) # 출력 모양
strides = (2*4,4*4,4) # 건너뛰기 ()

win = st.as_strided(a, shape=shape, strides=strides)
print(win)



[[[          0           1]
  [          4           5]]

 [[          2           3]
  [          6           7]]

 [[          4           5]
  [          8           9]]

 [[          6           7]
  [  521259415 -2147481344]]

 [[          8           9]
  [-1901228944         330]]

 [[  521259415 -2147481344]
  [         49          58]]

 [[-1901228944         330]
  [         43          50]]

 [[         49          58]
  [         44          93]]

 [[         43          50]
  [          0           0]]

 [[         44          93]
  [  523028884 -2147481088]]

 [[          0           0]
  [-1896928592         330]]

 [[  523028884 -2147481088]
  [-1870191808         330]]]


In [134]:
a[1:+2,]

array([1])

In [135]:
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)

In [131]:
a = np.arange(10)
b = np.arange(10)



SyntaxError: invalid syntax (<ipython-input-131-962c7f5b2706>, line 5)

In [144]:
inH = inW = 256
scale = 2

nStep = inW - scale
memorySize = 1
shape = (nStep,scale,scale) # 출력 모양
a=np.zeros((256,256))

temp = []
for row in range(0,inH - scale):
    strides = (1*memorySize,inW*memorySize,memorySize) # 건너뛰기 ()
    win = st.as_strided(a[row:row+scale,:], shape=shape, strides=strides)
    temp.append(win.mean())

print(temp[0])


0.0


In [147]:
a = np.array([[[1,2],[3,4]],[[3,4],[5,6]]])
a.mean()

3.5

In [171]:
g = np.array([0,0])
g = list(map(np.mean, a))
print(g)

[2.5, 4.5]


In [178]:
a = np.array([[1,2,3]])
np.append(a,[[2,3,4]],axis=0)


array([[1, 2, 3],
       [2, 3, 4]])

In [179]:
print(np.array([1,2,3]))

[1 2 3]
