In [3]:
import numpy as np
import random

In [6]:
data = np.random.randn(2,3)
dataList = [ [random.random() for _ in range(3)] for _ in range(2) ]
print(data[0][1])
print(dataList[0][1])

0.45628137267268554
0.5523440608417954


In [14]:
# 1. 행렬 연산 비교 (리스트, 넘파이)

print(data[0,1])
#dataList[0,1]
A = [[10,20],[30,40]]
B = [[1,2],[3,4]]

AA = np.array(A)
BB = np.array(B)

print(AA)
print(BB)

print("A+B List: 행렬 연산 불가")
print(A+B)
print("A+B Array: 행렬 연산 가능")
print(AA+BB)

0.45628137267268554
[[10 20]
 [30 40]]
[[1 2]
 [3 4]]
A+B List:
[[10, 20], [30, 40], [1, 2], [3, 4]]
A+B Array:
[[11 22]
 [33 44]]


In [20]:
#2. shape, ndim

# vector = 1차원 배열
# matrix = 2차원 배열
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
print(v1.shape)
print(v1.ndim)


v1+v2
v1*v2

(3,)
1


array([ 4, 10, 18])

In [21]:
#3. 형변환
print("data")
print(data)
print("data.reshape()")
print(data.reshape(3,2))

data
[[ 0.15942362  0.45628137 -0.68027968]
 [ 0.11724499 -0.27593376 -1.39825929]]
data.reshape()
[[ 0.15942362  0.45628137]
 [-0.68027968  0.11724499]
 [-0.27593376 -1.39825929]]


In [25]:
#4. 행렬 연산
A = np.array([[10,20],[30,40]])
B = np.array([[1,2],[3,4]])


print("대수곱셈")
print(A*B)
print("행렬곱")
print(np.dot(A,B))

[[10 20]
 [30 40]] [[1 2]
 [3 4]] [[ 10  40]
 [ 90 160]]
대수곱셈
[[ 10  40]
 [ 90 160]]
행렬곱
[[ 70 100]
 [150 220]]


In [27]:
# 5.BroadCasting

print(A*2)
print(A*3)

[[20 40]
 [60 80]]
[[ 30  60]
 [ 90 120]]


In [46]:
# 6.Slicing
list1 = [n for n in range(10,70,10)]
A2 = np.array(list1)
print(A2)

# 변환
B2 = A2.reshape(2,3)
print("B2")
print(B2)

# 선택
print("B2 0열 모든행")
print(B2[:,0],"\n")

# 메모리 공유(주의)
C1 = B2
C1[0,0] = 11111
print(B2, "B2도 바뀜")

# 복사
C2 = B2.copy()
C2[0,0] = 123456
print(C2)
print(B2)


[10 20 30 40 50 60]
B2
[[10 20 30]
 [40 50 60]]
B2 0열 모든행
[10 40] 

[[11111    20    30]
 [   40    50    60]] B2도 바뀜
[[123456     20     30]
 [    40     50     60]]
[[11111    20    30]
 [   40    50    60]]


In [41]:
# 리스트 -> 행렬 -> 변환
list2 = [ n for n in range(10, 90, 10) ]
AA = np.array(list2).reshape(2,4)
print(AA,"AA \n")

# 이터레이트 생성 (순회용)
iterator = np.nditer(AA, flags=['multi_index'], op_flags=['readwrite'])

# ** 이터레이터 기본 구문 
while not iterator.finished:
    idx = iterator.multi_index
    print(AA[idx])
    iterator.iternext()
# 실전에선 iterator를 사용하면 속도가 느려짐.
# 브로드 캐스팅등이 가장 빠름 

[[10 20 30 40]
 [50 60 70 80]] AA 

10
20
30
40
50
60
70
80


In [58]:
# matrix 붙이기 axis =0 -> 밑에 axis = 1 -> 옆에
BB = np.array([1,2,3,4])
BB = BB.reshape(1,4)
CC = np.concatenate((AA,BB), axis=0)
print(CC, "\n")

# 여러개도 가능
CC = np.array([100, 200, 300, 400])
CC = CC.reshape(1,4)
DD = np.concatenate((AA,BB,CC), axis=0)
print(DD,"\n")




[[10 20 30 40]
 [50 60 70 80]] AA
[[10 20 30 40]
 [50 60 70 80]
 [ 1  2  3  4]] 

[[ 10  20  30  40]
 [ 50  60  70  80]
 [  1   2   3   4]
 [100 200 300 400]] 



In [71]:
# 파일 불러오기
data = np.loadtxt("C:/images/csv/cat02.csv", delimiter=",", dtype=np.int32)
# delimiter = 구분자, dtype = 받아올 타입

# 특정 값 가져오기
rows = data[:,2] # 모든 행의 2번째 열(픽셀) 값
print(rows[0:5],type(rows))

# 모양 그대로 가져오기
rows = data[:,2:3] 
print(rows[0:5],type(rows))






[109 113 103 109 103] <class 'numpy.ndarray'>
[[109]
 [113]
 [103]
 [109]
 [103]] <class 'numpy.ndarray'>


TypeError: 'float' object cannot be interpreted as an integer

In [73]:
np.zeros([2,3], dtype=np.uint8)

array([[0, 0, 0],
       [0, 0, 0]], dtype=uint8)